baseURL = ""
languageCode = "en-us"
theme = "hugo-theme-hamburg-new"
title = "My New Hugo Site"
[[menu.Homepage1]]
identifier = "petinsurance"
name = "Test"
title = "Pet Insurance"
url = "test"
weight = 1
[[menu.Homepage1.1]]
identifier = "petinsurancegroup"
title = "Pet Insurance"
[[menu.Homepage1.1.1]]
identifier = "doginsurance"
title = "Dog Insurance"
url = "/dog-insurance"
[[menu.Homepage1.1.2]]
identifier = "catinsurance"
title = "Cat Insurance"
url = "/cat-insurance"
[[menu.Homepage1.1.3]]
identifier = "petwellnessplans"
title = "Pet Wellness Plans"
url = "/routine-care"
[[menu.Homepage2]]
identifier = "whypetsbest"
title = "Why Pets Best"
weight = 1
[[menu.Homepage3]]
identifier = "resources"
title = "Resources"
weight = 1
[params]
assetsPath = ""
