baseURL = ""
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-hamburg-new"
[params]
	assetsPath = ""
[menu]
	[[menu.Homepage3]]
		identifier = "petinsurance"
		title = "Pet Insurance"
	[[menu.Homepage2]]
		identifier = "whypetsbest"
		title = "Why Pets Best"
	[[menu.Homepage3]]
		identifier = "resources"
		title = "Resources"
